# Generated by Django 5.2 on 2025-10-20
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0004_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='service_status',
            field=models.CharField(
                choices=[('NO_PURCHASED', 'Sin servicio'), ('PENDING', 'Pendiente'), ('COMPLETED', 'Completado')],
                default='NO_PURCHASED',
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='profile',
            name='service_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
