# Generated by Django 5.2.6 on 2025-10-21 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0005_profile_service_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SNP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rsid', models.CharField(max_length=20, verbose_name='rsID')),
                ('genotipo', models.CharField(max_length=10, verbose_name='Genotipo')),
                ('fenotipo', models.TextField(verbose_name='Fenotipo')),
                ('categoria', models.CharField(blank=True, max_length=50, null=True, verbose_name='Categoría')),
                ('importancia', models.IntegerField(blank=True, null=True, verbose_name='Nivel de importancia')),
            ],
            options={
                'verbose_name': 'SNP',
                'verbose_name_plural': 'SNPs',
                'db_table': 'snps',
                'indexes': [models.Index(fields=['rsid'], name='snps_rsid_789da6_idx'), models.Index(fields=['categoria'], name='snps_categor_03f777_idx')],
                'unique_together': {('rsid', 'genotipo')},
            },
        ),
        migrations.CreateModel(
            name='UserSNP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_associations', to='autenticacion.snp', verbose_name='SNP')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_snps', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'SNP de Usuario',
                'verbose_name_plural': 'SNPs de Usuarios',
                'db_table': 'user_snps',
                'indexes': [models.Index(fields=['user'], name='user_snps_user_id_4cc690_idx'), models.Index(fields=['snp'], name='user_snps_snp_id_4178b9_idx')],
                'unique_together': {('user', 'snp')},
            },
        ),
    ]
