# Generated by Django 5.2.6 on 2025-10-22 03:22

import autenticacion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0006_add_snp_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rut',
            field=models.CharField(help_text='RUT en formato XXXXXXX-R (ejemplo: 12345678-9 o 1234567-K)', max_length=12, null=True, unique=True, validators=[autenticacion.models.validate_rut_format], verbose_name='RUT'),
        ),
    ]
