# Generated by Django 5.2.6 on 2025-10-23 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0007_profile_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='report_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='report_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
