# Generated by Django 5.2.6 on 2025-10-30 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0008_profile_report_filename_profile_report_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='snp',
            name='alelo_alternativo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Alelo alternativo'),
        ),
        migrations.AddField(
            model_name='snp',
            name='alelo_referencia',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Alelo de referencia'),
        ),
        migrations.AddField(
            model_name='snp',
            name='cromosoma',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Cromosoma'),
        ),
        migrations.AddField(
            model_name='snp',
            name='fecha_actualizacion',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AddField(
            model_name='snp',
            name='fuente_base_datos',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fuente de base de datos'),
        ),
        migrations.AddField(
            model_name='snp',
            name='magnitud_efecto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Magnitud del efecto'),
        ),
        migrations.AddField(
            model_name='snp',
            name='nivel_riesgo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nivel de riesgo'),
        ),
        migrations.AddField(
            model_name='snp',
            name='posicion',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Posición genómica'),
        ),
        migrations.AddField(
            model_name='snp',
            name='tipo_evidencia',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de evidencia'),
        ),
        migrations.AddIndex(
            model_name='snp',
            index=models.Index(fields=['cromosoma'], name='snps_cromoso_b4fdbb_idx'),
        ),
        migrations.AddIndex(
            model_name='snp',
            index=models.Index(fields=['nivel_riesgo'], name='snps_nivel_r_816f9e_idx'),
        ),
    ]
