# Generated by Django 5.2.6 on 2025-10-30 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0009_snp_alelo_alternativo_snp_alelo_referencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snp',
            name='importancia',
        ),
    ]
