# Generated by Django 5.2.6 on 2025-10-31 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0010_remove_snp_importancia'),
    ]

    operations = [
        migrations.AddField(
            model_name='snp',
            name='af_continente',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='Frecuencia Alélica - Continente'),
        ),
        migrations.AddField(
            model_name='snp',
            name='af_pais',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='Frecuencia Alélica - País'),
        ),
        migrations.AddField(
            model_name='snp',
            name='continente',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Continente'),
        ),
        migrations.AddField(
            model_name='snp',
            name='fuente_continente',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fuente - Continente'),
        ),
        migrations.AddField(
            model_name='snp',
            name='fuente_pais',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fuente - País'),
        ),
        migrations.AddField(
            model_name='snp',
            name='pais',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='snp',
            name='poblacion_continente',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Población - Continente'),
        ),
        migrations.AddField(
            model_name='snp',
            name='poblacion_pais',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Población - País'),
        ),
    ]
