# Generated by Django 5.2.6 on 2025-10-31 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0012_reset_snp_ids'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='snp',
            unique_together=set(),
        ),
    ]
