# Generated by Django 5.2.6 on 2025-10-31 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0013_remove_snp_unique_constraint'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='snp',
            unique_together={('rsid', 'genotipo', 'fenotipo', 'categoria')},
        ),
    ]
