# Generated by Django 5.2.6 on 2025-10-31 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0014_alter_snp_unique_together'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE snps DROP CONSTRAINT IF EXISTS snps_rsid_genotipo_fenotipo_categoria_ee4f6489_uniq CASCADE;",
            reverse_sql=None,
        ),
    ]
