# Generated by Django 5.2.6 on 2025-10-31 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0015_remove_all_unique_constraints'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""WITH numbered_snps AS (
                SELECT id, ROW_NUMBER() OVER (ORDER BY id) as new_id FROM snps
            )
            UPDATE snps SET id = numbered_snps.new_id FROM numbered_snps WHERE snps.id = numbered_snps.id;
            SELECT setval('snps_id_seq', (SELECT MAX(id) FROM snps) + 1);""",
            reverse_sql=None,
        ),
    ]
