# Generated by Django 5.2.6 on 2025-11-23 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0016_reset_snp_ids_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='snp',
            name='grupo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Grupo del Rasgo'),
        ),
    ]
