# Generated by Django 5.2.6 on 2025-11-27 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0017_snp_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sample_code',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, unique=True, verbose_name='Código de Muestra'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sample_code_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de creación del código'),
        ),
    ]
