# Generated by Django 5.2.6 on 2025-11-28
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0018_profile_sample_code_profile_sample_code_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='arrival_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Llegada confirmada en recepción'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sample_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de envío al laboratorio'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sample_status',
            field=models.CharField(choices=[('PENDING_COLLECTION', 'Pendiente de toma'), ('COLLECTED_PENDING_ANALYSIS', 'Muestra tomada / Pendiente de análisis'), ('SENT_TO_LAB', 'Enviada al laboratorio'), ('RECEIVED_AT_LAB', 'Recibida en laboratorio')], db_index=True, default='PENDING_COLLECTION', max_length=40, verbose_name='Estado de la muestra'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sample_taken_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de toma de muestra'),
        ),
    ]

