# Generated by Django 5.2.6 on 2025-11-28
from django.db import migrations


def create_reception_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.get_or_create(name="RECEPCION")


class Migration(migrations.Migration):
    dependencies = [
        ('autenticacion', '0019_profile_sample_tracking'),
    ]

    operations = [
        migrations.RunPython(create_reception_group, migrations.RunPython.noop),
    ]

