# Generated by Django 5.2.6 on 2025-12-16 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0021_fix_constraints'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='snp',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='usersnp',
            unique_together=set(),
        ),
    ]
