# Generated by Django 5.2.6 on 2025-12-16 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0022_alter_snp_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='snp',
            name='snps_rsid_789da6_idx',
        ),
        migrations.RemoveIndex(
            model_name='snp',
            name='snps_categor_03f777_idx',
        ),
        migrations.RemoveIndex(
            model_name='snp',
            name='snps_cromoso_b4fdbb_idx',
        ),
        migrations.RemoveIndex(
            model_name='snp',
            name='snps_nivel_r_816f9e_idx',
        ),
    ]
