# Generated by Django 5.2.6 on 2025-12-22 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0020_create_reception_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacogeneticSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Sistema')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Sistema Farmacogenético',
                'verbose_name_plural': 'Sistemas Farmacogenéticos',
            },
        ),
        migrations.AddField(
            model_name='snp',
            name='pharmacogenetic_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snps', to='autenticacion.pharmacogeneticsystem', verbose_name='Sistema Farmacogenético'),
        ),
    ]
