# Generated by Django 5.2.6 on 2025-12-22 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0024_pharmacogeneticsystem_snp_pharmacogenetic_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snp',
            name='pharmacogenetic_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snps', to='autenticacion.pharmacogeneticsystem', verbose_name='Sistema Farmacogenetico'),
        ),
    ]
