[build]
builder = "dockerfile"

[deploy]
startCommand = "sh -c 'python manage.py migrate --noinput && python manage.py collectstatic --noinput || true && gunicorn sequoh.wsgi:application --bind 0.0.0.0:${PORT:-8000} --workers 3 --timeout 120'"