/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/head.glb 
Author: hangar79 (https://sketchfab.com/hangar79)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/male-facial-muscles-ecorche-23c2d4af8088418d8b3ea9057ec88ff4
Title: Male Facial-muscles Ecorche
*/

import React, { useState, useMemo } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'

// Mapeo de partes faciales
const PART_NAMES = {
  Object_2: 'Nariz',
  Object_3: 'Músculo Orbicular del Ojo',
  Object_4: 'Músculo Nasal',
  Object_5: 'Músculo Cigomático Mayor',
  Object_6: 'Músculo Cigomático Menor',
  Object_7: 'Músculo Orbicular de la Boca',
  Object_8: 'Músculo Risorio',
  Object_9: 'Músculo Masetero',
  Object_10: 'Músculo Temporal',
  Object_11: 'Labios',
  Object_12: 'Músculo Depresor del Ángulo de la Boca',
  Object_13: 'Músculo Depresor del Labio Inferior',
  Object_14: 'Músculo Mental',
  Object_15: 'Ojo Izquierdo',
  Object_16: 'Músculo Occipital',
  Object_17: 'Músculo Auricular',
  Object_18: 'Ojo Derecho',
  Object_19: 'Músculo Prócer',
  Object_20: 'Músculo Elevador del Labio Superior',
  Object_21: 'Músculo Elevador del Ala de la Nariz',
  Object_22: 'Músculo Depresor del Tabique',
  Object_23: 'Músculo Transverso de la Nariz',
}

export function Head({ onPartClick, ...props }) {
  const { nodes, materials } = useGLTF('/head.glb')
  const [selectedPart, setSelectedPart] = useState(null)

  // Crear materiales únicos para cada mesh
  const meshMaterials = useMemo(() => {
    const mats = {}
    Object.keys(PART_NAMES).forEach(key => {
      mats[key] = materials.material_0.clone()
    })
    return mats
  }, [materials])

  const handlePartClick = (e, partKey) => {
    e.stopPropagation()
    const partName = PART_NAMES[partKey] || partKey
    setSelectedPart(partKey)
    if (onPartClick) onPartClick(partName)
  }

  // Actualizar colores de materiales cuando cambia la selección
  useMemo(() => {
    Object.keys(meshMaterials).forEach(key => {
      meshMaterials[key].color.set(selectedPart === key ? 'orange' : 'white')
    })
  }, [selectedPart, meshMaterials])

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={meshMaterials.Object_2} onClick={(e) => handlePartClick(e, 'Object_2')} />
        <mesh geometry={nodes.Object_3.geometry} material={meshMaterials.Object_3} onClick={(e) => handlePartClick(e, 'Object_3')} />
        <mesh geometry={nodes.Object_4.geometry} material={meshMaterials.Object_4} onClick={(e) => handlePartClick(e, 'Object_4')} />
        <mesh geometry={nodes.Object_5.geometry} material={meshMaterials.Object_5} onClick={(e) => handlePartClick(e, 'Object_5')} />
        <mesh geometry={nodes.Object_6.geometry} material={meshMaterials.Object_6} onClick={(e) => handlePartClick(e, 'Object_6')} />
        <mesh geometry={nodes.Object_7.geometry} material={meshMaterials.Object_7} onClick={(e) => handlePartClick(e, 'Object_7')} />
        <mesh geometry={nodes.Object_8.geometry} material={meshMaterials.Object_8} onClick={(e) => handlePartClick(e, 'Object_8')} />
        <mesh geometry={nodes.Object_9.geometry} material={meshMaterials.Object_9} onClick={(e) => handlePartClick(e, 'Object_9')} />
        <mesh geometry={nodes.Object_10.geometry} material={meshMaterials.Object_10} onClick={(e) => handlePartClick(e, 'Object_10')} />
        <mesh geometry={nodes.Object_11.geometry} material={meshMaterials.Object_11} onClick={(e) => handlePartClick(e, 'Object_11')} />
        <mesh geometry={nodes.Object_12.geometry} material={meshMaterials.Object_12} onClick={(e) => handlePartClick(e, 'Object_12')} />
        <mesh geometry={nodes.Object_13.geometry} material={meshMaterials.Object_13} onClick={(e) => handlePartClick(e, 'Object_13')} />
        <mesh geometry={nodes.Object_14.geometry} material={meshMaterials.Object_14} onClick={(e) => handlePartClick(e, 'Object_14')} />
        <mesh geometry={nodes.Object_15.geometry} material={meshMaterials.Object_15} onClick={(e) => handlePartClick(e, 'Object_15')} />
        <mesh geometry={nodes.Object_16.geometry} material={meshMaterials.Object_16} onClick={(e) => handlePartClick(e, 'Object_16')} />
        <mesh geometry={nodes.Object_17.geometry} material={meshMaterials.Object_17} onClick={(e) => handlePartClick(e, 'Object_17')} />
        <mesh geometry={nodes.Object_18.geometry} material={meshMaterials.Object_18} onClick={(e) => handlePartClick(e, 'Object_18')} />
        <mesh geometry={nodes.Object_19.geometry} material={meshMaterials.Object_19} onClick={(e) => handlePartClick(e, 'Object_19')} />
        <mesh geometry={nodes.Object_20.geometry} material={meshMaterials.Object_20} onClick={(e) => handlePartClick(e, 'Object_20')} />
        <mesh geometry={nodes.Object_21.geometry} material={meshMaterials.Object_21} onClick={(e) => handlePartClick(e, 'Object_21')} />
        <mesh geometry={nodes.Object_22.geometry} material={meshMaterials.Object_22} onClick={(e) => handlePartClick(e, 'Object_22')} />
        <mesh geometry={nodes.Object_23.geometry} material={meshMaterials.Object_23} onClick={(e) => handlePartClick(e, 'Object_23')} />
      </group>
    </group>
  )
}

useGLTF.preload('/head.glb')
