/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/model.glb 
Author: Diego Luján García (https://sketchfab.com/diegoluga)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/male-full-body-ecorche-ab11ebff89224f03bd75efede1164cf6
Title: Male Full Body Ecorche
*/

import React, { useState } from 'react'
import { useGLTF } from '@react-three/drei'

// Mapeo de nombres técnicos a partes anatómicas
// AJUSTA ESTOS NOMBRES según lo que represente cada objeto en tu modelo
const PART_NAMES = {
  Object_3: 'Cabeza',
  Object_5: 'Cuello',
  Object_7: 'Torso Superior',
  Object_9: 'Torso Inferior',
  Object_11: 'Brazo Derecho',
  Object_13: 'Antebrazo Derecho',
  Object_15: 'Mano Derecha',
  Object_17: 'Brazo Izquierdo',
  Object_19: 'Antebrazo Izquierdo',
  Object_21: 'Mano Izquierda',
  Object_23: 'Pierna Derecha',
  Object_25: 'Rodilla Derecha',
  Object_27: 'Pie Derecho',
  Object_29: 'Pierna Izquierda',
  Object_31: 'Rodilla Izquierda',
  Object_33: 'Pie Izquierdo',
}

export function Model({ onPartClick, ...props }) {
  const { nodes, materials } = useGLTF('/model.glb')
  const [selectedPart, setSelectedPart] = useState(null)

  const handlePartClick = (e, partKey) => {
    e.stopPropagation()
    const partName = PART_NAMES[partKey] || partKey
    setSelectedPart(partKey)
    if (onPartClick) onPartClick(partName)
  }

  const getMeshColor = (partKey) => {
    return selectedPart === partKey ? 'orange' : 'white'
  }

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh 
          geometry={nodes.Object_3.geometry} 
          material={materials.defaultMat_12}
          onClick={(e) => handlePartClick(e, 'Object_3')}
          material-color={getMeshColor('Object_3')}
        />
        <mesh 
          geometry={nodes.Object_5.geometry} 
          material={materials.defaultMat_11}
          onClick={(e) => handlePartClick(e, 'Object_5')}
          material-color={getMeshColor('Object_5')}
        />
        <mesh 
          geometry={nodes.Object_7.geometry} 
          material={materials.defaultMat_10}
          onClick={(e) => handlePartClick(e, 'Object_7')}
          material-color={getMeshColor('Object_7')}
        />
        <mesh 
          geometry={nodes.Object_9.geometry} 
          material={materials.defaultMat_9}
          onClick={(e) => handlePartClick(e, 'Object_9')}
          material-color={getMeshColor('Object_9')}
        />
        <mesh 
          geometry={nodes.Object_11.geometry} 
          material={materials.material_1}
          onClick={(e) => handlePartClick(e, 'Object_11')}
          material-color={getMeshColor('Object_11')}
        />
        <mesh 
          geometry={nodes.Object_13.geometry} 
          material={materials.defaultMat_8}
          onClick={(e) => handlePartClick(e, 'Object_13')}
          material-color={getMeshColor('Object_13')}
        />
        <mesh 
          geometry={nodes.Object_15.geometry} 
          material={materials.defaultMat_7}
          onClick={(e) => handlePartClick(e, 'Object_15')}
          material-color={getMeshColor('Object_15')}
        />
        <mesh 
          geometry={nodes.Object_17.geometry} 
          material={materials.defaultMat_6}
          onClick={(e) => handlePartClick(e, 'Object_17')}
          material-color={getMeshColor('Object_17')}
        />
        <mesh 
          geometry={nodes.Object_19.geometry} 
          material={materials.defaultMat_5}
          onClick={(e) => handlePartClick(e, 'Object_19')}
          material-color={getMeshColor('Object_19')}
        />
        <mesh 
          geometry={nodes.Object_21.geometry} 
          material={materials.defaultMat_4}
          onClick={(e) => handlePartClick(e, 'Object_21')}
          material-color={getMeshColor('Object_21')}
        />
        <mesh 
          geometry={nodes.Object_23.geometry} 
          material={materials.defaultMat_3}
          onClick={(e) => handlePartClick(e, 'Object_23')}
          material-color={getMeshColor('Object_23')}
        />
        <mesh 
          geometry={nodes.Object_25.geometry} 
          material={materials.defaultMat_2}
          onClick={(e) => handlePartClick(e, 'Object_25')}
          material-color={getMeshColor('Object_25')}
        />
        <mesh 
          geometry={nodes.Object_27.geometry} 
          material={materials.defaultMat_1}
          onClick={(e) => handlePartClick(e, 'Object_27')}
          material-color={getMeshColor('Object_27')}
        />
        <mesh 
          geometry={nodes.Object_29.geometry} 
          material={materials.material_0}
          onClick={(e) => handlePartClick(e, 'Object_29')}
          material-color={getMeshColor('Object_29')}
        />
        <mesh 
          geometry={nodes.Object_31.geometry} 
          material={materials.defaultMat_0}
          onClick={(e) => handlePartClick(e, 'Object_31')}
          material-color={getMeshColor('Object_31')}
        />
        <mesh 
          geometry={nodes.Object_33.geometry} 
          material={materials.defaultMat}
          onClick={(e) => handlePartClick(e, 'Object_33')}
          material-color={getMeshColor('Object_33')}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/model.glb')
